config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'
  get 'about', to: 'landing#about'

  resources :users, only: [:show, :new, :create] do
    member do
      post :change_project
    end
  end

  resources :stages, only: [:create] do
    collection do
      get :display
    end
  end

  resources :projects, only: [:index, :show, :new, :create] do
    resources :invitations, only: [:create, :destroy]
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :stages
  has_many :users, through: :stages
  has_many :invitations

  validates :project_name, presence: true,
                           uniqueness: true,
                           length: { minimum: 3 },
                           format: { with: /\A[0-9a-zA-Z\ \-]+\z/, message: "Invalid project name" }


  def total_labor_time
    get_stages_by('labor').count * 30
  end

  def total_clear
   get_stages_by('long_rest').count
  end

  def get_stages_by(stage_type)
   self.stages.where(stage_type: stage_type)
  end
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stages
  has_many :owned_projects, foreign_key: 'user_id', class_name: 'Project'
  has_many :projects, through: :stages
  has_many :invitations

  validates :username, presence: true,
                       uniqueness: true,
                       length: { minimum: 3 },
                       format: { with: /\A[0-9a-zA-Z]+\z/, message: "can only contain letters and numbers." }

  validates :password, on: :create,
                       presence: true,
                       length: { minimum: 3 },
                       format: { with: /\A[0-9a-zA-Z]+\z/, message: "can only contain letters and numbers." }

  has_secure_password

  def total_labor_time
    get_stages_by('labor').count * 30
  end

  def total_rest_time
     get_stages_by('short_rest').count * 5 + total_clear() * 15
  end

  def total_clear
    get_stages_by('long_rest').count
  end

  def get_stages_by(stage_type)
    self.stages.where(stage_type: stage_type)
  end

  def total_by_project_and_stage(project_id, stage)
    count = self.stages.where(project_id: project_id).where(stage_type: stage).count

    case stage
    when 'labor'
      return count * 30
    when 'short_rest'
      return count * 5
    when 'long_rest'
      return count * 15
    end
  end

  def has_misc_stages?
    self.stages.where(project_id: nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user, :current_project

  def logged_in?
    session[:user_id].nil? ? false : true
  end

  def current_user
    User.find(session[:user_id])
  end

  def current_project
    session[:current_project]
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    invitation = Invitation.new(user_id: params[:user_id], project_id: params[:project_id])

    if invitation.save
      respond_to do |format|
        format.js do
          @user = User.find(params[:user_id])
          render 'create'
        end
      end
    else

    end
  end

  def destroy
    respond_to do |format|
      format.js do
        @project = Project.find(params[:project_id])
        Invitation.delete(params[:id])

        if params[:accept] == 'true'
          @accept = true
          Stage.create(user: current_user, project: @project)
        end
        render layout: false
      end
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :send_to_stages

  def index; end

  private

  def send_to_stages
    if logged_in?
      redirect_to display_stages_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(get_params)
    @project.owner = current_user

    if @project.save
      flash[:notice] = 'Project successfully saved: ' + @project.project_name
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def add_user
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  private

  def get_params
    params.require(:project).permit(:project_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :send_to_profile, except: [:destroy]
  before_action :logged_in?, only: :destroy

  def new; end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to display_stages_path
    else
      flash[:error] = 'Incorrect user name or password.'
      redirect_to login_path
    end
  end

  def destroy
    flash[:notice] = 'You are now logged out.'
    session[:user_id] = nil
    session[:current_project] = nil
    redirect_to root_path
  end

  private

  def send_to_profile
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController

  def create
    if logged_in?
      @stage = Stage.new
      respond_to do |format|
        format.json do
          @stage.stage_type = params[:stage_type]
          @stage.user = current_user
          @stage.project = Project.find_by(project_name: current_project) if current_project
          @stage.save
        end
      end
    end
    render nothing: true
  end

  def display; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :send_to_profile, except: [:show, :change_project]
  before_action :logged_in?, only: :show

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(get_params)

    if @user.save
      flash[:notice] = "You are now registered."
      redirect_to user_path(@user)
      session[:user_id] = @user.id
    else
      render 'new'
    end
  end

  def change_project
    session[:current_project] = params[:current_project]
    puts params[:current_project]
    respond_to do |format|
      format.js do
      end
    end
  end

  private

  def get_params
    params.require(:user).permit(:username, :password, :timezone)
  end

  def send_to_profile
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def labor_time_prettyfied(time)
    if time == 0
      'Not Yet Begun'
    else
      (time.to_f / 60).round(2).to_s + ' Hrs.'
    end
  end

  def labor_as_percentage(contribution, total)
    return 'N/A' if total == 0
    ((contribution.to_f / total) * 100).to_i.to_s + ' %'
  end

  def addable_user(project_id, user)
    project = Project.find(project_id)
    users = []
    Invitation.where(project_id: project_id).each { |invite| users << invite.user }

    inviteable_users = (User.all - users)

    if project.owner.username != user.username &&
       !project.users.include?(user) &&
       inviteable_users.include?(user)
       return true
    end
    false
  end
end

app/views/invitations/add_project.js.erb
$("#invitations li:contains('<%= @project.project_name %>') small:contains('<%= @project.owner.username %>')").closest('li').hide();
alert('hello');

<% if @accept %>
  <% change_project_link = link_to @project.project_name, change_project_user_path(id: current_user.id, current_project: @project.project_name), class: 'make_current_project' + (current_project == @project.project_name ? ' active_project' : ''), method: :post, remote: true %>
  <% labor = labor_time_prettyfied(current_user.total_by_project_and_stage(@project.id, 'labor')) %>
  <% view_link = link_to 'View', project_path(@project), class: 'view_project' %>
  <% puts 'this worked but didnt' %>
  $("#current_projects ul").append('hdlefas');

  $("#current_projects ul").append("<li><%= change_project_link %>:<%= labor %><%= view_link %></li>")
<% end %>

app/views/invitations/create.js.erb
$("li:contains('<%= @user.username %>')").hide();

app/views/invitations/destroy.js.erb
$("#invitations li:contains('<%= @project.project_name %>') small:contains('<%= @project.owner.username %>')").closest('li').hide();

<% if @accept %>
  <% change_project_link = link_to @project.project_name, change_project_user_path(id: current_user.id, current_project: @project.project_name), class: 'make_current_project' + (current_project == @project.project_name ? ' active_project' : ''), method: :post, remote: true %>
  <% labor = labor_time_prettyfied(current_user.total_by_project_and_stage(@project.id, 'labor')) %>
  <% view_link = link_to 'View', project_path(@project), class: 'view_project' %>

  $("#current_projects ul").append('<li><%= change_project_link %> :  <%= labor %><%= view_link %></li>');
<% end %>

app/views/landing/index.html.erb
<div id="login_container">
  <div class="landing_links"><%= link_to "Login", login_path %></div>
  <span>Or</span>
  <div class="landing_links"><%= link_to "Register", new_user_path %></div>
  <small><%= link_to "Try It Without Logging In", display_stages_path %></small>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'error' %>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<h1>
  <%= link_to root_path do %>
    Pommy
    <i id="fav-header" class="fa fa-hand-peace-o" aria-hidden="true"></i>
  <% end %>
</h1>

<% if logged_in? %>
  <%= link_to 'Logout', logout_path, id: 'logout' %>
  <%= link_to 'Profile', user_path(current_user.id), id: 'profile' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pommy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'test', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
  <header>
    <%= render 'layouts/nav' %>
  </header>
  <main>
    <div id="path_directions">
      <div id="path_icons">
        <span class="path_container">
          <i class="fa fa-chevron-right" aria-hidden="true" data-stage="1">
            <div class="circle" data-stage="1"></div>
            <span class="line" data-stage="2"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-coffee" aria-hidden="true" data-stage="3">
            <div class="circle" data-stage="3"></div>
            <span class="line" data-stage="3"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-chevron-right" aria-hidden="true" data-stage="4">
            <div class="circle" data-stage="4"></div>
            <span class="line" data-stage="4"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-coffee" aria-hidden="true" data-stage="5">
            <div class="circle" data-stage="5"></div>
            <span class="line" data-stage="5"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-chevron-right" aria-hidden="true" data-stage="6">
            <div class="circle" data-stage="6"></div>
            <span class="line" data-stage="6"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-coffee" aria-hidden="true" data-stage="7">
            <div class="circle" data-stage="7"></div>
            <span class="line" data-stage="7"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-chevron-right" aria-hidden="true" data-stage="8">
            <div class="circle" data-stage="8"></div>
            <span class="line" data-stage="8"></span>
          </i>
        </span>

        <span class="path_container">
          <i class="fa fa-smile-o" aria-hidden="true" data-stage="9">
            <div class="circle" data-stage="9"></div>
          </i>
        </span>
      </div>
    </div>

    <%= render 'layouts/messages' %>

    <%= yield %>
  </main>
</body>
</html>

app/views/projects/new.html.erb
<%= render 'shared/title', title: 'New Project' %>

<%= render 'shared/errors', model: @project %>

<%= form_for @project do |f| %>
  <%= f.label :project_name %>
  <%= f.text_field :project_name %>
  <br>
  <%= f.submit 'Submit' %>
<% end %>

app/views/projects/show.html.erb
<%= render 'shared/title', title: @project.project_name %>

<ul id="overview" class="project_overview">
  <li>
    <span>Total Clears:</span>
    <span><%= @project.total_clear %></span>
  </li>
  <li>
    <span>Total Time Spent Working:</span>
    <span><%= labor_time_prettyfied(@project.total_labor_time) %></span>
  </li>
  <li>
    <p>Owner: <%= @project.owner.username %></p>
  </li>
</ul>

<% if @project.owner == current_user %>
  <div id="project">
    <div id="project_divider"></div>
    <div class="project_container">
      <div id="project_users">
        <h5>Contributors</h4>
        <% if @project.users.any? %>
          <ul id="participants" class="owner">
          <% @project.users.uniq.each do |user| %>
            <li>
              <span class="contributor">
                <%= user.username %>
              </span>

              <% user_time = user.total_by_project_and_stage(@project.id, 'labor') %>
              <span class="contrib_abs_time">
                <%= labor_time_prettyfied(user_time) %>
              </span>:
              <span class="contrib_rel_time">
                <%= labor_as_percentage(user_time, @project.total_labor_time) %>
              </span>
            </li>
          <% end %>
          </ul>
        <% end %>
      </div>
    </div><!--

    --><div class="projects_container">
      <div id="invite_users">
        <h5>Add Users</h5>
        <% if User.all.any? %>
        <ul id="users">
          <% User.all.each do |user| %>
            <% if addable_user(@project.id, user)  %>
               <li>
                 <%= user.username %>
                 <%= link_to project_invitations_path(@project, user_id: User.find_by(username: user.username)), class: 'add_user', remote: true, method: :post do %>
                   <i class="fa fa-plus-square" aria-hidden="true"></i>
                 <% end %>
               </li>
            <% end %>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
<div id="participants" class="viewer">
  <h5>Contributors</h4>
  <% if @project.users %>
  <ul id="participants">
  <% @project.users.uniq.each do |user| %>
    <li>
      <span class="contributor">
        <%= user.username %>
      </span>

      <% user_time = user.total_by_project_and_stage(@project.id, 'labor') %>
      <span class="contrib_abs_time">
        <%= labor_time_prettyfied(user_time) %>
      </span>:
      <span class="contrib_rel_time">
        <%= labor_as_percentage(user_time, @project.total_labor_time) %>
      </span>
    </li>
  <% end %>
  </ul>
  <% end %>
</div>
<% end %>

app/views/shared/_current_project.html.erb
<div id="current_working_project">

</div>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <div id="errors">
  <h3>The following error(s) were found:</h3>
  <ul>
    <% model.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/shared/_title.html.erb
<h2><%= title %></h2>

app/views/stages/display.html.erb
<%= render 'shared/title', title: current_project %>

<div id="time_container">
  <span id="minutes">30</span>
  <span id="seconds">00</span>
  <br>
  <a id="start_end_time" href="#">Begin</a>
</div>

app/views/users/change_project.js.erb
$(".active_project").toggleClass("active_project");
<% if current_project.nil? %>
  $("a:contains('Misc')").toggleClass("active_project");
<% else %>
  $("a:contains('<%= current_project %>')").toggleClass("active_project");
<% end %>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'Register' %>

<%= render 'shared/errors', model: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :timezone %>
  <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones %>
  <br>
  <%= f.submit 'Register' %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/title', title: 'Overview' %>

<ul id="overview">
  <li>
    <span>Total Clears:</span>
    <span><%= @user.total_clear %></span>
  </li>
  <li>
    <span>Total Time Spent Working:</span>
    <span><%= labor_time_prettyfied(@user.total_labor_time) %></span>
  </li>
</ul>


<%= render 'shared/title', title: 'Projects' %>
<%= link_to 'New Project', new_project_path, id: 'new_project_link' %>

<div id="projects">
  <div id="projects_divider"></div>
  <div class="projects_container">
  <div id="current_projects">
    <h4>Current Projects</h4>
    <ul>
      <li>
        <%= link_to change_project_user_path(id: @user.id, current_project: nil), class: 'make_current_project' + (current_project == nil ? ' active_project' : ''), method: :post, remote: true do %>
          Misc:
        <% end %>

        <%= labor_time_prettyfied(@user.total_by_project_and_stage(nil, 'labor')) %>
      </li>
      <% if @user.owned_projects.any? || @user.projects.any? %>
        <% (@user.owned_projects + @user.projects).uniq.each do |project| %>
          <li>
            <%= link_to change_project_user_path(id: @user.id, current_project: project.project_name), class: 'make_current_project' + (current_project == project.project_name ? ' active_project' : ''), method: :post, remote: true do %>
              <%= project.project_name  %>
            <% end %>
            :
            <%= labor_time_prettyfied(@user.total_by_project_and_stage(project.id, 'labor')) %>
            <%= link_to 'View', project_path(project), class: 'view_project' %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  </div><!--

  --><div class="projects_container">
  <div id="invitations">
    <h4>Invitations</h4>
    <ul>
      <% @user.invitations.each do |invite| %>
        <li>
          <%= invite.project.project_name %> <br>
          <small>by <%= invite.project.owner.username %></small>

          <%= link_to 'View', project_path(invite.project) %>

          <%= link_to project_invitation_path(invite.project.id, invite.id, accept: false), remote: true, method: :delete do %>
            <i class="fa fa-minus-square" aria-hidden="true"></i>
          <% end %>

          <%= link_to project_invitation_path(invite.project.id, invite.id, accept: true), remote: true, method: :delete do %>
            <i class="fa fa-plus-square" aria-hidden="true"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>